name: 184-final
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib  # plots
  - tqdm  # progress bars
  - jaxtyping  # shape annotations
  - gymnasium[classic-control]  # environment
  - stable-baselines3=2.3.*  # expert policy
  - pytorch=2.3.*  # training
  - pygame=2.5.*  # classic control
